config/routes.rb
Rails.application.routes.draw do
  resources :empleados

   root 'empleados#index'

end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
    
     include Paperclip::Glue
    
    has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController
  before_action :set_empleado, only: [:show, :edit, :update, :destroy]

  # GET /empleados
  # GET /empleados.json
  def index
    @empleados = Empleado.all
    @homepage = true
  end

  # GET /empleados/1
  # GET /empleados/1.json
  def show
  end

  # GET /empleados/new
  def new
    @empleado = Empleado.new
  end

  # GET /empleados/1/edit
  def edit
  end

  # POST /empleados
  # POST /empleados.json
  def create
    @empleado = Empleado.new(empleado_params)

    respond_to do |format|
      if @empleado.save
        format.html { redirect_to @empleado, notice: 'Empleado was successfully created.' }
        format.json { render :show, status: :created, location: @empleado }
      else
        format.html { render :new }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empleados/1
  # PATCH/PUT /empleados/1.json
  def update
    respond_to do |format|
      if @empleado.update(empleado_params)
        format.html { redirect_to @empleado, notice: 'Empleado was successfully updated.' }
        format.json { render :show, status: :ok, location: @empleado }
      else
        format.html { render :edit }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empleados/1
  # DELETE /empleados/1.json
  def destroy
    @empleado.destroy
    respond_to do |format|
      format.html { redirect_to empleados_url, notice: 'Empleado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empleado
      @empleado = Empleado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empleado_params
      params.require(:empleado).permit(:nombre, :fechacumpleaños, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/views/empleados/_form.html.erb
<%= form_for @empleado, html: { multipart: true } do |f| %>
  <% if @empleado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@empleado.errors.count, "error") %> prohibited this empleado from being saved:</h2>

      <ul>
      <% @empleado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :fechacumpleaños %><br>
    <%= f.text_field :fechacumpleaños %>
  </div>
  <div class="field">
    
  <%= f.file_field :avatar, as: :file %>

  </div>
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/empleados/edit.html.erb
<h1>Editing empleado</h1>



<%= render 'form' %>

<%= link_to 'Show', @empleado %> |
<%= link_to 'Back', empleados_path %>

app/views/empleados/index.html.erb
<body class="homepage">
  



<div class="container">
  <div class="row">
    <h1 class="centrar cum">Grupo de Apoyo Administrativo Complejo Sur Itagüí</h1>

   <hr>
    <section id="pinBoot">
       <% @empleados.each do |empleado| %>
      <article class="white-panel imagen"><%= image_tag empleado.avatar.url(:medium) %>
        <h4 class="centrar"><%= empleado.nombre %></h4>
        <p class="centrar"><%= empleado.fechacumpleaños %></p>
        <p>
          
        <%#= link_to 'Show', empleado %>
        <%= link_to 'Edit', edit_empleado_path(empleado) %>
        <%= link_to 'Destroy', empleado, method: :delete, data: { confirm: 'Are you sure?' } %>
        
        </p>
      </article>
      
       

      <% end %>

    </section>


    <hr>


  </div>
  <p>
   
<%= link_to 'New Empleado', new_empleado_path %>


  </p>

</div>
</body>

app/views/empleados/new.html.erb
<h1>New empleado</h1>



<%= render 'form' %>

<%= link_to 'Back', empleados_path %>

app/views/empleados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @empleado.nombre %>
  
</p>
<p>
  <strong>imagen:</strong>
  <%= image_tag @empleado.avatar.url(:medium) %>
</p>




<p>
  <strong>Fechacumpleaños:</strong>
  <%= @empleado.fechacumpleaños %>
</p>

<%= link_to 'Edit', edit_empleado_path(@empleado) %> |
<%= link_to 'Back', empleados_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cumpleaños Apoyo Administrativo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body class="<%= @homepage ? 'homepage' : ''%>">
  


<%= yield  %>


</body>
</html>